# Exploration Production Construction
An Exploration Production Construction is a registration object that contains data on subsurface works that fall under the Mining Act. These include works for the exploration, extraction, and storage of minerals and geothermal energy, such as boreholes, mine systems, and salt caverns.

In [1]:
import brodata

In [ ]:
epc = brodata.epc.ExplorationProductionConstruction.from_bro_id("EPC000000000140")

Show the construction history.

In [6]:
epc.constructionHistory

        date                       name
0 1983-07-13       aanlegBoorgatGestart
1 1984-09-26  wettelijkeStatusGewijzigd

Show the borehols segments. In this case there is only one segment.

In [4]:
epc.boreholeSegment

,boreholeSegmentCode,boreholeSegmentName,boreholeSegmentCategory,purpose,drillingStartDate,drillingEndDate,dateOfDisclosure
0,1394,HAASTRECHT-02,primair,opsporenDelfstof,None,None,2003-01-01

Show the rest of the contents of the Exploration Production Construction.

In [8]:
dict = epc.to_dict()
dict.pop("boreholeSegment")
dict.pop("constructionHistory")
dict

{'broId': 'EPC000000000140',
 'coordinateTransformation': 'RDNAPTRANS2018MV0',
 'corrected': 'nee',
 'deliveryAccountableParty': '95206957',
 'deliveryContext': 'archiefoverdracht',
 'deregistered': 'nee',
 'id': 'BRO_0004',
 'latestAdditionTime': '2025-09-30T15:18:01+02:00',
 'legalStatus': 'buitenGebruikMijnbouw',
 'localVerticalReferencePoint': 'NAP',
 'location': <POINT (113875.53 445039.64)>,
 'objectRegistrationTime': '2025-09-29T19:16:28+02:00',
 'offset': 0.0,
 'originalOffset': '6.010',
 'originalVerticalReferencePoint': 'draaitafel',
 'owner': None,
 'qualityRegime': 'IMBRO/A',
 'registrationStatus': 'aangevuld',
 'reregistered': 'nee',
 'sourceReference_chamberOfCommerceNumber': '27376655',
 'standardizedLocation': <POINT (4.788 51.992)>,
 'startDate': Timestamp('1983-07-13 00:00:00'),
 'underReview': 'nee',
 'verticalDatum': 'NAP'}